### ISSUE TITLE
SSL is not supported

### ISSUE THREAD

**Issue by kilianc** [popomore/koa-proxy#10]
since the host in the headers is not properly rewritten SSL verification fails.

**Comment by egeland** [comment]
I got this issue as well.

Here's my very simple route (forgive its simplicity, I'm still a JS and Koa n00b):
```
router.get('/api-gh/:user', proxy({
  url: 'https://api.github.com/users/' + this.user
}));
```
And here's what the error is:
```
Error: Hostname/IP doesn't match certificate's altnames: "Host: localhost. is not in the cert's altnames: DNS:*.github.com, DNS:github.com"
      at Object.checkServerIdentity (tls.js:210:15)
      at TLSSocket.<anonymous> (_tls_wrap.js:934:31)
      at TLSSocket.emit (events.js:104:17)
      at TLSSocket._finishInit (_tls_wrap.js:460:8)
```

How can we make this work?

**Comment by popomore** [comment]
You can specify [request](https://github.com/request/request) options by `requestOptions`.

@egeland  Maybe you can set `strictSSL` false

**Comment by workzer** [comment]
Example from the last answer of @popomore :
```javascript
server.use(proxy({
		host: 'myUrl',
                match: /^\/proxy\//,
		requestOptions: {
			strictSSL: false
		}
	}));
