### ISSUE TITLE
Add custom headers

### ISSUE THREAD

**Issue by kilianc** [popomore/koa-proxy#11]
How do I add an `Authorization` header to the proxied req ?

**Comment by popomore** [comment]
PR is welcome.

**Comment by kilianc** [comment]
this is how I fixed it:

```js
app.use(mount('/es', function *(next) {
  this.header.host = process.env.ES_HOST
  this.header.authorization = 'Basic ' + process.env.ES_AUTH
  yield* next
}))
```

in my case I am proxying to elasticsearch on bonsai.io

I will try to submit a PR but I can't promise to be able to this week.

**Comment by lizell** [comment]
This PR, #20, allows you to control the options of the proxied request, including headers.
