### ISSUE TITLE
Cookies are retained across requests

### ISSUE THREAD

**Issue by GreenGremlin** [popomore/koa-proxy#23]
There needs to be a way to disable the request cookie jar. When running selenium tests koa-proxy retains cookies across browser sessions. Even clearing cookies does not stop koa-proxy from forwarding the cookies. Please expose the jar setting to make it easier to disable this behavior.

**Comment by GreenGremlin** [comment]
This makes it very difficult to run selenium tests, which rely on a clean session to run properly.

**Comment by marr** [comment]
lgtm

**Comment by GreenGremlin** [comment]
The PR currently has failing tests. I'm certain the failures are not due to my changes, I believe they are due to updating node versions on travis. I've already spent quite a bit of time trying to figure out why they are failing, but I still don't really have an idea. I pinged the original author of the failing tests on the PR, hopefully he is able to help.
