### ISSUE TITLE
Support options of request

### ISSUE THREAD

**Issue by thxCode** [popomore/koa-proxy#38]
I use koa-proxy to proxy some https website, but the certificate has expired, so koa-proxy error on `[Error: certificate revoked]`. But I found co-request options to set
[https://github.com/request/request#requestoptions-callback ](strictSSL) = false, can ignore this error.

Change code like this:  `options || (options = {jar: true});
  var request = coRequest.defaults(options);` to support request options, is it Ok?

**Comment by popomore** [comment]
You can use `options.requestOptions`
