### ISSUE TITLE
Any way to make this work with a socket?

### ISSUE THREAD

**Issue by Taconut** [popomore/koa-proxy#52]
Hi! I'd like to use this, but one of the endpoints that I'm proxying is a websocket. How can I proxy that over too?

**Comment by popomore** [comment]
I'm afraid not, this is a http proxy.

**Comment by Taconut** [comment]
Thanks. 
By chance, would you happen to know of any alternative utilities that would let me tunnel a proxy through koa?

**Comment by popomore** [comment]
Sorry, I don't know. But I think nginx is more powerful, stable, and have good performance than node server.

**Comment by Taconut** [comment]
Thanks for the tip! Looks like I can just set up nginx with a few reverse proxies!
